# Generated by Django 4.2.3 on 2023-10-04 00:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0002_alter_settings_company_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="settings",
            old_name="reoder_default",
            new_name="reorder_default",
        ),
    ]
