# Generated by Django 4.2.3 on 2023-07-11 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0002_product_quantity_alter_product_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="SaleItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="Quantity")),
                (
                    "unit_price",
                    models.FloatField(
                        blank=True, default=0.0, help_text="In XAF", null=True
                    ),
                ),
                (
                    "total_price",
                    models.FloatField(
                        blank=True, default=0.0, help_text="In XAF", null=True
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sale_items",
                        to="products.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(max_length=250, verbose_name="Transaction ID"),
                ),
                ("quantity", models.PositiveIntegerField(default=0)),
                ("total_sale_price", models.FloatField(default=0.0)),
                ("date_created", models.DateTimeField(blank=True)),
                ("items", models.ManyToManyField(to="sales.saleitem")),
                (
                    "sales_man",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
