# Generated by Django 4.2.3 on 2023-07-23 22:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0002_remove_sale_quantity_sale_validated_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="saleitem",
            name="created",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
