# Generated by Django 4.2.3 on 2023-07-24 06:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0003_saleitem_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="transaction_id",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Transaction ID"
            ),
        ),
    ]
