# Generated by Django 4.2.3 on 2023-07-24 06:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0004_alter_sale_transaction_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="validated",
            field=models.BooleanField(default=False),
        ),
    ]
