# Generated by Django 4.2.3 on 2023-07-24 06:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0005_alter_sale_validated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="date_created",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
