# Generated by Django 4.2.3 on 2023-07-14 20:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
