# Generated by Django 4.2.3 on 2023-07-11 21:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="quantity",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Products's Quantity"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.FloatField(
                blank=True,
                default=0.0,
                help_text="In XAF",
                null=True,
                verbose_name="Product's Price",
            ),
        ),
    ]
