# Generated by Django 4.2.3 on 2023-07-14 21:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_category_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, null=True, verbose_name="Product Slug"),
        ),
    ]
